// Canonical CHIEF capability vocabulary.
//
// These ids are what the control plane reports. Several of them are enforced
// by an existing grant (web:read is web:search, workspace:read is finance:read)
// so stored policies keep working. Connector capabilities live on the connector
// registry, not in this list.

import { Capability } from "../core/capabilities.js";

function entry(fields) {
  return Object.freeze({
    connector: null,
    reason: null,
    ...fields,
    confirmation: fields.confirmation ?? "none",
    tools: Object.freeze([...(fields.tools ?? [])]),
  });
}

export function builtInCapabilities() {
  return [
    entry({
      id: "memory:read",
      kind: "read",
      effect: "read",
      grant: Capability.MEMORY_READ,
      tools: ["memory_read", "kg_lookup"],
      confirmation: "none",
      readiness: "read",
      summary: "Read this user's stored facts and knowledge-graph entries.",
    }),
    entry({
      id: "memory:write",
      kind: "action",
      effect: "write",
      grant: Capability.MEMORY_WRITE,
      tools: ["memory_write", "kg_link", "write_handoff"],
      confirmation: "required",
      readiness: "action",
      summary: "Store a fact, link the graph, or replace the working handoff.",
    }),
    entry({
      id: "schedule:read",
      kind: "read",
      effect: "read",
      grant: Capability.SCHEDULE_READ,
      tools: ["schedule_list", "schedule_runs", "schedule_outcome"],
      confirmation: "none",
      readiness: "read",
      summary: "Read schedules, runs, and outcomes.",
    }),
    entry({
      id: "schedule:create",
      kind: "action",
      effect: "write",
      grant: Capability.SCHEDULE_CREATE,
      tools: ["schedule_create", "schedule_update", "schedule_pause", "schedule_resume"],
      confirmation: "required",
      readiness: "action",
      summary: "Create or change a schedule.",
    }),
    entry({
      id: "schedule:cancel",
      kind: "action",
      effect: "destructive",
      grant: Capability.SCHEDULE_CREATE,
      tools: ["schedule_cancel"],
      confirmation: "required",
      readiness: "action",
      summary: "Cancel a schedule. This needs a fresh confirmation.",
    }),
    entry({
      id: "finance:read",
      kind: "read",
      effect: "read",
      grant: Capability.FINANCE_READ,
      tools: ["finance_summary"],
      confirmation: "none",
      readiness: "freedomFinancial",
      summary: "Read Freedom Financial position data.",
    }),
    entry({
      id: "workspace:read",
      kind: "read",
      effect: "read",
      grant: Capability.FINANCE_READ,
      tools: ["workspace_plan_summary"],
      confirmation: "none",
      readiness: "freedomFinancial",
      summary: "Read the Freedom Financial workspace plan slice.",
    }),
    entry({
      id: "skill:read",
      kind: "read",
      effect: "read",
      grant: Capability.SKILL_READ,
      tools: ["skill_view"],
      confirmation: "none",
      readiness: "read",
      summary: "Read a bundled procedure.",
    }),
    entry({
      id: "web:read",
      kind: "read",
      effect: "external",
      grant: Capability.WEB_SEARCH,
      tools: ["web_search"],
      confirmation: "none",
      readiness: "web",
      summary: "Search the public web. Enforced by web:search.",
    }),
    entry({
      id: "module:access",
      kind: "read",
      effect: "read",
      grant: Capability.MODULE_ACCESS,
      tools: ["freedom_financial_access_status"],
      confirmation: "none",
      readiness: "read",
      summary: "See whether Freedom Financial read access is on.",
    }),
    entry({
      id: "module:access:set",
      kind: "action",
      effect: "high_impact",
      grant: Capability.MODULE_ACCESS,
      tools: ["freedom_financial_access_set"],
      confirmation: "required",
      readiness: "action",
      summary: "Turn Freedom Financial read access on or off.",
    }),
    entry({
      id: "conversation:read",
      kind: "read",
      effect: "read",
      grant: Capability.CONVERSATION_READ,
      tools: ["conversation_search", "conversation_retrieve"],
      confirmation: "none",
      readiness: "read",
      summary: "Search and read this user's conversations.",
    }),
    entry({
      id: "conversation:write",
      kind: "action",
      effect: "write",
      grant: Capability.CONVERSATION_WRITE,
      tools: ["conversation_rename", "conversation_archive", "conversation_restore"],
      confirmation: "required",
      readiness: "action",
      summary: "Rename, archive, or restore a conversation.",
    }),
    entry({
      id: "conversation:delete",
      kind: "action",
      effect: "destructive",
      grant: Capability.CONVERSATION_DELETE,
      tools: ["conversation_delete"],
      confirmation: "required",
      readiness: "action",
      summary: "Permanently delete a conversation.",
    }),
    entry({
      id: "settings:read",
      kind: "read",
      effect: "read",
      grant: Capability.SETTINGS_READ,
      tools: ["settings_read"],
      confirmation: "none",
      readiness: "read",
      summary: "Read this user's timezone.",
    }),
    entry({
      id: "settings:write",
      kind: "action",
      effect: "write",
      grant: Capability.SETTINGS_WRITE,
      tools: ["settings_update"],
      confirmation: "required",
      readiness: "action",
      summary: "Change this user's timezone.",
    }),
    entry({
      id: "code:read",
      kind: "read",
      effect: "read",
      grant: Capability.CODE_READ,
      tools: ["code_tree", "code_read", "code_search"],
      confirmation: "none",
      readiness: "code",
      summary:
        "Read the configured Freedom OS repository. This is not a shell and not a user GitHub account.",
    }),
    entry({
      id: "capability:read",
      kind: "read",
      effect: "read",
      grant: Capability.CAPABILITY_READ,
      tools: ["capability_discover"],
      confirmation: "none",
      readiness: "read",
      summary: "Read this capability inventory.",
    }),
    entry({
      id: "tool:invoke",
      kind: "action",
      effect: "external",
      grant: Capability.TOOL_INVOKE,
      tools: ["mcp_invoke"],
      confirmation: "required",
      readiness: "action",
      summary: "Call a configured MCP tool.",
    }),
    entry({
      id: "data:read",
      kind: "read",
      effect: "read",
      grant: Capability.DATA_READ,
      tools: [],
      confirmation: "none",
      readiness: "static-unavailable",
      reason:
        "No generic data query is registered. Freedom OS records are read through the specific capabilities in this inventory.",
      summary: "Generic Freedom OS record query.",
    }),
    entry({
      id: "data:write",
      kind: "action",
      effect: "write",
      grant: Capability.DATA_WRITE,
      tools: [],
      confirmation: "required",
      readiness: "static-unavailable",
      reason:
        "No generic data write is registered. Changes go through the specific action that owns the record.",
      summary: "Generic Freedom OS record write.",
    }),
    entry({
      id: "code:execute",
      kind: "action",
      effect: "external",
      grant: Capability.CODE_EXECUTE,
      tools: [],
      confirmation: "required",
      readiness: "static-unavailable",
      reason: "Code execution is not registered. CHIEF has no shell, interpreter, or deploy tool.",
      summary: "Run code.",
    }),
    entry({
      id: "network:fetch",
      kind: "action",
      effect: "external",
      grant: Capability.NETWORK_FETCH,
      tools: [],
      confirmation: "required",
      readiness: "static-unavailable",
      reason: "Arbitrary network fetch is not registered. Public web search is web:read.",
      summary: "Fetch an arbitrary URL.",
    }),
  ];
}
